# Copyright (C) 2021 SanCloud Ltd
# SPDX-License-Identifier: Apache-2.0

FROM ghcr.io/sancloudltd/iot-dev:dev

ENV TOOLCHAIN_VENDOR=bootlin
ENV TOOLCHAIN_ARCH=armv7-eabihf
ENV TOOLCHAIN_LIBC=glibc
ENV TOOLCHAIN_BRANCH=stable
ENV TOOLCHAIN_VERSION=2021.11-1
ENV TOOLCHAIN_FULLNAME=${TOOLCHAIN_ARCH}--${TOOLCHAIN_LIBC}--${TOOLCHAIN_BRANCH}-${TOOLCHAIN_VERSION}

RUN wget --progress=dot:mega \
        "https://toolchains.bootlin.com/downloads/releases/toolchains/${TOOLCHAIN_ARCH}/tarballs/${TOOLCHAIN_FULLNAME}.tar.bz2" && \
    tar -C /opt -xf "${TOOLCHAIN_FULLNAME}.tar.bz2" && \
    rm -f "${TOOLCHAIN_FULLNAME}.tar.bz2" && \
    ln -sfn "${TOOLCHAIN_FULLNAME}" /opt/toolchain

COPY setenv "/opt/toolchain/setenv"
