# Copyright (C) 2021 SanCloud Ltd
# SPDX-License-Identifier: Apache-2.0

FROM docker.io/crops/yocto:ubuntu-20.04-base

RUN wget --progress=dot:mega https://bootstrap.pypa.io/get-pip.py && \
    python3 get-pip.py && \
    rm get-pip.py && \
    python3 -m pip install --no-cache-dir kas && \
    mkdir -p ~/.ssh && \
    echo 'StrictHostKeyChecking accept-new' >> ~/.ssh/config
