# Copyright (C) 2021 SanCloud Ltd
# SPDX-License-Identifier: Apache-2.0

FROM docker.io/library/ubuntu:20.04

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
        build-essential cmake ninja-build mosquitto libmosquitto-dev \
        libjson-c-dev device-tree-compiler bison flex wget libssl-dev \
        libgmp3-dev libmpc-dev bc ca-certificates libncurses-dev \
        u-boot-tools git clang-tidy cppcheck rsync zlib1g-dev \
        autoconf automake libtool file openssh-client && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
